cozy-labs/konnectors

client/app/locales/en.coffee
client/app/locales/fr.coffee

The output was "Konnector Free: Konnector Free: the notification content".

Fixed: error notifications had the prefix twice

---

package.json

By default it's the same as Calendar, which is annoying for ISEN users (they have 4 apps, 2 have the same background).

Added: specific icon's background color

---

server/lib/konnector_poller.coffee

This is a backport of a fix that seems to work on ISEN branch.

Prevent starting a timer twice

---

server/konnectors/githubcommits.coffee

```
TypeError: Cannot read property 'sha' of undefined
at /usr/local/cozy/apps/konnectors/server/konnectors/githubcommits.coffee:158:50
at parseBody (/usr/local/cozy/apps/konnectors/node_modules/request-json/main.js:35:12)
at Request._callback (/usr/local/cozy/apps/konnectors/node_modules/request-json/main.js:77:18)
at Request.self.callback (/usr/local/cozy/apps/konnectors/node_modules/request/request.js:121:22)
at Request.emit (events.js:98:17)
at Request.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/request/request.js:978:14)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/request/request.js:929:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickCallback (node.js:448:13) …
```

Fix bug when commit have no parents

---

server/lib/link_bank_operation.coffee
server/models/bankoperation.coffee

Fixes https://github.com/cozy-labs/konnectors/issues/52
This PR allows also to update already linked operations.
One question remains (just editorial) : 
do I rather use another name for fileName and fileMime ? (using only lower case field names)

Save file name and file mime for clean link to bankoperation

---

server/lib/naming.coffee
server/lib/save_data_and_file.coffee
tests/naming.coffee

Following the discussion of https://github.com/cozy-labs/konnectors/issues/85, I add the capability to parameterize file name for bills saved via a konnector as files.
@ZeHiro could you review it and tell me if it matches your expectation?

Allow to have a more advanced naming for bills

---

build/server/konnectors/githubcommits.js
server/konnectors/githubcommits.coffee

Currently, only public commits are imported. With this PR, private commits are also imported.

Import private github commits

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/numericable.coffee

Numericable

---

server/konnectors/isen.coffee
server/models/event.coffee
server/models/requests.coffee

As a result, events where not created when imported from ISEN connector.

Fixed: use caldavuri to store ISEN's ID for events, because setting a predefined ID is forbidden in cozydb

---

server/lib/importer.coffee

Exception found in the logs of a user:
```
/usr/local/cozy/apps/konnectors/build/server/lib/importer.js:26
if (err && Object.keys(err).length > 0) {
^
TypeError: Object.keys called on non-object
at Function.keys (native)
at /usr/local/cozy/apps/konnectors/build/server/lib/importer.js:26:25
at /usr/local/cozy/apps/konnectors/build/server/models/konnector.js:146:22
at /usr/local/cozy/apps/konnectors/node_modules/cozydb/lib/model.js:34:14
at /usr/local/cozy/apps/konnectors/node_modules/cozydb/lib/cozymodel.js:112:18
at parseBody (/usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
at IncomingMessage.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
at IncomingMessage.emit …
```

Fix exception when handling a server error

---

server/konnectors/bouyguestelecom.coffee

It seems they changed their URL. And the date is now "Février 2016" for example so we need to set the french locale to moment.

Fix bouygues telecom konnector (urls and date parsing)

---

server/konnectors/linkedin.js

Fix error
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:374:25)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at getKonnectorModules (/home/florian/Coding/NodeJS/cozy/konnectors/build/server/lib/konnector_hash.js:28:23)
at Object.<anonymous> (/home/florian/Coding/NodeJS/cozy/konnectors/build/server/lib/konnector_hash.js:34:18)
at Module._compile (module.js:410:26)

Add "use strict" to ES6 linkedin connector to avoid runtime error

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
client/app/views/konnector.coffee
package.json
server/konnectors/kimsufi_ca.coffee
server/konnectors/kimsufi_eu.coffee
server/konnectors/ovh_ca.coffee
server/konnectors/ovh_eu.coffee
server/konnectors/runabove.coffee
server/konnectors/soyoustart_ca.coffee
server/konnectors/soyoustart_eu.coffee
server/lib/base_ovh_konnector.coffee
server/lib/ovh_fetcher.coffee

Feel free to change appKey/appSecret, these are just for tests.
This konnector is only for ovh-eu but there are other available services:
* OVH Europe: ovh-eu (actual)
* OVH North-America: ovh-ca
* RunAbove: runabove-ca
* SoYouStart Europe: soyoustart-eu
* SoYouStart North-America: soyoustart-ca
* Kimsufi Europe: kimsufi-eu
* Kimsufi North-America: kimsufi-ca
We choose the service when we generate the login url. So IMHO there are two options:
* Allow the user to choose the service with a select box in a "OVH global konnector". The drawback is they won't be able to have multiple simultaneous services (ovh-eu and kimsufi-eu for example).
* Create a "global ovh backend" and one konnector per service (so 7 konnectors). The drawback is duplication of code (boring code like translations etc)
I …

Add OVH konnector

---

server/konnectors/ameli.coffee

The comma value is not interpreted by the parseFloat function

Fix float format for ameli konnector

---

.eslintrc.json
package.json
scripts/lint.sh
server/konnectors/ameli.coffee
server/konnectors/birthdays.js
server/konnectors/ical_feed.js

Eslint config changes:
* Do not complain about strict mode: it doesn't fit the Node 4 behavior.
* Do not complain when err is declared several times: it makes impossible to
nest callbacks.
* Do not complain when functions are mentioned before being defined. It
doesn't fit with the way we write connectors.
This commits changes the lint script too, in order to include all konnector
files. Finally, it comes with linting of JS files and missing linting of coffee
files.

Fix linting for JS files

---

server/konnectors/ameli.coffee

As mention on #216, the last debian version considers the Ameli's certificate issuer as untrusted.
This should be a temporary patch, waiting for the [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812708) to be resolved on debian.

Fix certificate issue

---

server/lib/link_bank_operation.coffee

I was looking at #213 and thought about a simple situation where the match would lead to the first situation: if we match the right operation first, but then there happens to be another operation which matches the criterias too, we'll end up clobbering the right operation to link. So I think the linking should try to minimize the difference in amount, at least, which is what this PR does.
Also: I've removed `minAmountDelta` and `maxAmountDelta`, as nobody were using those in the konnectors directory. It also makes the comparisons simpler.
Also changed the default value of `amountDelta` to 0.001, because IEEE754 and comparing two floating point values for equality is equivalent to comparing the bits. If you're not convinced, run this piece of code: `if (0.1 + 0.2 !== 0.3) alert("LET THE …

Try a smarter operation / bill match algorithm;

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/captain_train.js
server/lib/link_bank_operation.coffee
server/models/bill.coffee

Fixes #178 
Buying tickets on Captain Train can lead to different operation labels: 'Capitain Train', 'Capitaine train' (for older operations), for Ouigo tickets bought on capitaine train, the operation is directly labelled 'Ouigo'. I then allowed to use an array as the operation identifier to allow to manage these situations. To maintain compatity with existing konnectors,  if the passed label is a string, it is put inside an array.
Capitain Train connector can also import refund bills, to be sure the bills are matched to the appropriate operation, in case on the same day, a train ticket is bought, and the same amount is refounded, the distinction was made between normal payments, and refunds. Refunds need do be declared as such, using isRefund attribute of the Bill object. 
Still known …

Konnector for captain train 

---

server/controllers/konnectors.coffee
server/lib/importer.coffee
server/lib/notification_handler.coffee

Manage notifications at the same location: previsously they were managed (the same) in the importer and the konnector controller.
This will help future maintenance of this function (previsously #250 was fixed only for automatic fetch).
Fixes the fact that only one notification could be sent for each konnector. Now one notification is raised per account.
Fixes empty notifications on manual fetch (fixes #250)

Improve notification management

---

README.md
client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/facebook_events.js

PR comment from @jacquarg 
A Konnector which add "accepted" Facebook event to a Calendar in the Cozy.
This Konnector is mainly a proof of concept of using OAuth2 API with a Cozy (which should open the door to about all modern APIs), in a confident way. Here, the Konnector use a redirect_uri proxy which is a simple page, hosted on github.io : https://github.com/jacquarg/jacquarg.github.io/blob/master/proxy_redirect/facebook_events/index.html
Actually, the Konnector requires to Copy/Past the token ; but everything is setup for automatic handling (with redirections, ...) - it's not done yet because Konnector UI don't provide easy access to the UI and routes.

Add a Facebook event konnector, which fetch user's event through FB OAuth2 API

---

.eslintrc.json
client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/sncf.js

Some orders are in the old html form so I kept the old `getEvents` function. Once they will have completely migrated to the new html pages we will be able to remove it.
The new html order page is built with Angular which eases the parsing because we can directly fetch the JSON from the API.
I modified the linter to allow max line length to 120 because some JQuery selectors are very long.
Closes https://github.com/cozy-labs/konnectors/issues/328

Fix sncf konnector (new html presentation)

---

server/konnectors/ovh_eu.coffee
server/konnectors/runabove.coffee

I changed the ovh application tokens for a better application name/description.
I can't add tokens for Kimsufi fr/ca, Soyoustart fr/ca and ovh ca because I don't have an account on these services.
The OVH support said me that we can create an account on each service by creating an order and stop at the payment step.  Maybe I'm an idiot, but I tried and it never worked.
If there is no objection, I'll create an issue for each these services so anyone in the community that is client of one of them could create the associated application tokens.

Add application token for runabove

---

server/konnectors/sfr_mobile.js

If there is no year provided when using moment, moment will use the current year.
SFR does not provide the year for the last bill, but I guess they would if the bill's year was different from the current year.
This PR simplifies the code and fixes the previous issue (mix of Date/moment instances).

Fix SFR mobile (wrong date handling)

---

client/app/views/konnector.coffee
server/controllers/konnectors.coffee
server/init/konnectors.coffee

Fixes #381
This does not remove the import warning when deleting a specific configuration, but only when deleting the whole configuration (all the accounts attached to the konnector). It is not easy to have a "by configuration" management of the warning, as the importErrorMessage is managed on the konnector level, not an the account level.

Reset import Error on deletion of an account

---

package.json
server/init/konnectors.coffee

Fixes unwanted errors when we start a watch task fromn a clean environment (clean clone and empty DS)

Fix env dev on clean clone

---

client/app/app.vue
client/app/components/examples/bar.vue
client/app/components/examples/foo.vue
client/app/index.js
client/app/plugins/vue-polyglot.js
client/package.json
server/controllers/index.coffee
server/views/index.jade

This PR enables two features in the Vue.js stack:
- vue-router: is now declared and loaded by index with an example set of routes
- vue-polyglot: to enable localization in templates through a vue filter

Add Vue tools and libs

---

README.md

Use the build status badge from master branch in README.md, to avoid having a "build failed" icon, while the master branch still builds fine.

Use build status on master branch in README.md

---

docs/client-side-connector-configuration.md
docs/client-side-use-cases-configuration.md
docs/client-side-usecases configuration.md
docs/server-side-configuration.md

This PR adds documentation about _use-cases_ and _categories_ behaviors in the new new client-side app.
📌 _Note about use-cases_: a _use-case_ is a way to sort available connectors in a different manner than simple categories, to provides to the user a way to discover some connectors organized by themes. You can see a mockup of the [_discover_ screen](https://marvelapp.com/77d7jfg/screen/14185063) (which presents configured _use-cases_), and a [_use-case_ screen](https://marvelapp.com/77d7jfg/screen/14184978) (accessible from the _discover_ screen, or in the onbaording) too.

Use-cases and Categories Documentation

---

server/lib/importer.coffee

Hi,
After upgrade to 0.7.4, Konnectors is heavily broken. This is due to a bad `path` use I made in #560, forgetting to `require` the package.
It was fixed by @jacquarg in #572 but only partially.
Some background about this:
* @m4dz asked me to use `path.join` everywhere in #560, which I did. Unfortunately, I forgot to `require('path')` in the files which were not already using it, which lead to a fatal error. Sorry for that... :/
* @jacquarg noticed it in #572 but only partially fixed it.
* @aenario published 0.7.4, and then the bug which was only on `master` branch (and not affecting much users) landed in every up-to-date Cozy :/
Then, I think, now, no-one can actually use Konnectors anymore. I tested this PR, and apart from #584 (which is unrelated I think), everything should be …

Fix for missing path include in #560

---

client/package.json

Note: `vuejs` is upgrading very often; lets upgrade dependencies very often too (or errors occur)
see also https://github.com/cozy-labs/konnectors/pull/578

`vue` and `vue-loader` modules version mismatch

---

client/app/views/konnector.coffee

This PR is related to #590. It adds a magic folder suggestion in the folder list, named `/Administration/{slug}`, if this folder doesn't already exists.

Add magic folder suggestion in folder list

---

server/controllers/konnectors.coffee
server/lib/save_data_and_file.coffee
server/models/folder.coffee

This PR introduces a way to create missing target folder on import. When an import is triggered, if the target folder doesn't exists (even if it's a nested folder), the full path is created. It's something similar to a `mkdir -p $TARGET_PATH` called in the DS _Folder_ doctype before executing import.

Create missing target folder on import

---

client/app/views/konnector.coffee

This PR introduces some changes in the magic folder for a konnector:
- adds the magic folder at end and select it if the konector isn't configured and the folder doesn't exists
- select the magic folder into the list if it already exists and the konnector isn't configured
- select the right folder (the selected one or the magic folder when created) when the konnector is configured
It should fix the select value issue.

Fix magic folder autoselect

---

client/app/views/konnector.coffee
server/controllers/konnectors.coffee
server/models/konnector.coffee

Konnectors has been added on onboarding. Thus, we want to add it on Cozy template.
Before registering, data-system does not have access to the encryption keys. 
However, the default password field is '{}'. 
Also take note that konnectors can't create konnectors during the intialization because data-system tries to encrypt it.
This PR changes default password field to allow konnector to create all konnectors before registering.

Change default password field

---

client/app/components/AccountDialog.jsx
client/app/components/AccountItem.jsx
client/app/components/UseCaseDialog.jsx
client/app/components/UseCasesList.jsx
client/app/contexts/cozy/index.json
client/app/index.jsx
client/app/styles/index.styl
docs/client-side-use-cases-configuration.md

Add use case dialogs content + some generic dialog component styles

---

client/app/components/AccountConfigForm.jsx
client/app/components/AccountDialog.jsx
client/app/lib/accountsHelper.js

Better default values

---

server/konnectors/trainline.js

Fixed it the hard way, as the stack v2 gonna be there soon, and the actual code is a mess of untestable coffee callbacks.
So, thanks to God only Trainline was having issue during migration, not the two other connectors being migrated (Virgin Mobile and Voyages SNCF). The only difference spotted was that no slug was specified for those ones. So in the first place I remove the slug from trainline konnector. It worked. There was no more duplicate of trainline konnector, but in DB, there was always two connectors  trainline and trainline_(captain_train).
Finally, Changing the name from "Trainline (Captain Train)" to "Trainline" fixed the whole issue.

[fix] Trainline duplicate

---

server/konnectors/ameli.coffee

The Ameli konnector was using the current year for its imports. So 2017 caused some troubles :)
References #655

Fix year bug in Ameli konnector

---

README.md
client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/malakoff_mederic.coffee

This PR adds the Malakoff Mederic connector. It is a health insurance, so it imports health reimbursements, just like the Ameli connector.
The login process is a bit ugly, mainly because the Malakoff website requires to parse a generated session id in a js page.
I tested on my own account (except for the bank link), and it seems fine.

Malakoff Mederic connector

---

server/controllers/konnectors.coffee
server/lib/poller.coffee

[fix] On deleting a config for a given konnector, reset the poller.

---

client/app/containers/ConnectorManagement.jsx
server/controllers/konnectors.coffee

, to avoid troubles with http redirect during Orange_mobile and orange_vod connectors.

Do identification in a popup for OAut-h konnector
