cozy-labs/konnectors

server/konnectors/bouyguestelecom.coffee
server/konnectors/github.coffee
server/lib/link_bank_operation.coffee
tests/link_bank_operation.coffee

Bank Operation linking was a little bit flawed. Here are a few fixes that should solve the problem. There were two bugs too in the Bouygues Telecom and Github konnectors.

Fix operation linking

---

README.md
client/app/locales/en.coffee
client/app/locales/fr.coffee
package.json
server/konnectors/freemobile.coffee

Known problem : 
If bad credential are used to try the import, and fail, if credentials are then corrected, it is impossible to import without restarting Konnectors (or maybe wait)
For update of ware, see commit comment (not tested with all konnectors, only free and freemobile)

Added Free Mobile connector

---

server/konnectors/free.coffee
server/konnectors/freemobile.coffee

Fix for  https://github.com/cozy-labs/konnectors/issues/75
and fix of bad credential management for freemobile konector
Fix timer for freemobile konnector: I topped it to 14 days (I had an unlinked operation). 14 is chosen to be also applicable for februray (28days) and avoid mismatch for this month

Fixes for free and freemobile konnectors 

---

server/konnectors/freemobile.coffee

Fixes https://github.com/cozy-labs/konnectors/issues/97

Fix logout of Free Mobile konnector

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/electrabel.coffee

Konnector to import Electrabel bills (Belgian energy provider)

Konnector Electrabel

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
package.json
server/konnectors/virginmobile.coffee

Fixes https://github.com/cozy-labs/konnectors/issues/129

Virgin Mobile konnector

---

build/server/lib/link_bank_operation.js
server/lib/link_bank_operation.coffee

Fix link between operation and imported file

---

server/konnectors/orange.coffee

Fix import orange

---

server/konnectors/isen.coffee
server/lib/link_bank_operation.coffee
server/lib/save_data_and_file.coffee
server/models/file.coffee
tests/lib_link_bank_operation.coffee
tests/models_file.coffee

That could lead to not find the factures to the bank operations

Correct UTC format issue

---

package.json
scripts/build.sh

Fix #189 
2 comments:
- `npm run build` doesn't build the `.map` files on my machine
- `npm test` is red, probably needs https://github.com/cozy-labs/konnectors/pull/185

Install missing dependencies

---

server/konnectors/virginmobile.coffee

Fixes #186.
Warning: I did not build the project, I only modified the source.

Virgin Mobile : fix error messages 

---

server/konnectors/numericable.coffee

Fix numericable konnector

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/online_net.coffee

Online.net has an API but infortunately not to find bills.
I didn't find how to add an icon to the sprite. Is there is a tool?

Add Online.net konnector

---

package.json
scripts/build.sh
scripts/lint.sh
scripts/tests.sh

It's 22M less to download and have on disk

Do not install client npm modules on production

---

package.json
scripts/build.sh
server/init/konnectors.coffee
server/konnectors/ical_feed.js
server/lib/base_konnector.js
server/models/event.coffee

Add a connector to fetch data from an Ical feed on a regular basis.
It comes with a base object for connectors to make the development of connectors easier.

Add Ical feed connector

---

package.json
scripts/build.sh
server/init/konnectors.coffee
server/konnectors/ical_feed.js
server/lib/base_konnector.js
server/lib/filter_existing.coffee
server/lib/link_bank_operation.coffee
server/lib/naming.coffee
server/lib/save_data_and_file.coffee
server/models/event.coffee

Fix update of operation link.
Fixes #206 
@frankrousseau , works on my installation, can you test?

Allow to link operations on non UTC servers.

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
package.json
server/konnectors/ameli.coffee

References the issue #197.
This konnector gives the possibility to import ameli health bills.

Add Ameli konnector

---

server/konnectors/ameli.coffee

Returns the error if the first request to ameli fails

Handle error in ameli konnector

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/sncf.js
server/models/bill.coffee

Add events and bills (without pdf) in Cozy. So we can see travels details in the calendar app :)
I'm sorry in advance, the code is ugly because the generated HTML by SNCF is a little bit difficult to parse (#frenchtech). Open to remarks.
Closes https://github.com/cozy-labs/konnectors/issues/205

Add SNCF konnector

---

build/server/lib/poller.js
server/lib/poller.coffee

Fixing problem exposed in https://forum.cozy.io/t/konnectors-nouveau-connecteur-pour-sfr/2348/30. The server read the date in english. There is some more work to do to handle the locale here.

Fixed server-side first import date

---

build/server/lib/importer.js
build/server/models/konnector.js
server/lib/importer.coffee
server/models/konnector.coffee

Fix the notifications not thrown anymore after multiple accounts

---

build/server/lib/importer.js
server/lib/importer.coffee

I could not test it on my instance but I suppose it will work.

Fix issue #250 : do not raise empty notification when nothing appened

---

server/models/konnector.coffee

Delete HTML balises of error message server side.

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/directenergie.js
server/lib/link_bank_operation.coffee

This provides a new Konnector for Direct Energie, that can fetch bills on the web site as well as save PDFs when there are some. It can also link bills to bank transactions: rather than simply using the entry's date, I've used the "paid at date", which is a field that might or might be not proposed by the document provider. Direct Energie does that, and the date delta is rather small when there's a "paidAtDate" field. I hope some other konnectors can also make use of this paidAt field :-) Note it's not saved in the DB, just used for linking bank operations to files.
Please let me know if I can do anything to ease the review :)

Direct Energie konnector

---

server/konnectors/captain_train.js

@frankrousseau 
This fix is good and tested. Except the case identified in #294, the captain train connector works perfectly
I let you build?

fix matching amount

---

server/konnectors/free.coffee

Free has updated their label. Previous label is kept for backward compatibility

Update free ISP operation labels

---

server/konnectors/free.coffee

Fix free connector

---

README.md
client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/aprr.js

i included all required modifications and made a lint test

adding APRR invoices fetch

---

client/app/locales/en.coffee
client/app/views/konnector.coffee
client/app/views/styles/_konnector.styl
client/app/views/templates/konnector.jade

This PR makes a konnector page more elegant.
It also removes a broken feature: the capability to select the first day of the import. The UX was misleading.

Improve konnector style

---

.eslintrc.json
package.json
server/konnectors/podcast.js
server/models/file.coffee

Podcast connector seemed broken due to my recent changes. I made it work but I had to remove the promises, it made hard to 
Sometimes request can't find the feed. I wasn't able to understand why it happens.

Fix podcast connector

---

server/konnectors/aprr.js
server/konnectors/vente_privee.js

Not the most elegant fix, but in order to make the konnector work, I will only enable the download of the lastest bill (the connector will download only one bill per fetch, the latest one...)
The user will need to fetch older bills by hand.
+linting APRR

Fixing issue 351

---

server/konnectors/sfr_mobile.js

Fix #383. 
I currently have only one bill (the last one) so I can't check I did not break the existing code though I did not modified it.

Fetch the last bill too for SFR mobile

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/materiel_net.js

Add Materiel.net connector

---

server/konnectors/numericable.js

Detect credential errors in numericable connector

---

client/app/views/konnector.coffee

Localize error message when on fetch

---

server/konnectors/online_net.coffee

Closes https://github.com/cozy-labs/konnectors/issues/465

Fix online.net konnector

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/bouyguesbox.coffee
server/konnectors/bouyguestelecom.coffee
server/konnectors/digitalocean.coffee
server/konnectors/github.coffee
server/konnectors/githubcommits.coffee
server/konnectors/googlecontacts.coffee
server/konnectors/ical_feed.js
server/konnectors/isen.coffee
server/konnectors/online_net.coffee
server/konnectors/orange.coffee
server/konnectors/rescuetime.coffee
server/konnectors/sfr_box.js
server/konnectors/sfr_mobile.js
server/konnectors/sncf.js
server/konnectors/sosh.coffee
server/lib/ovh_fetcher.coffee

Fix bad credentials error not displayed

---

README.md
server/konnectors/runabove.coffee

Fix Runabove connector not visible

---

server/konnectors/githubcommits.coffee

Make github username check case-insensitive

---

server/konnectors/ameli.coffee

This should fix the current Ameli's konnector state. I've successfully tested  with my account, but as usual, more tests are welcomed :)

Update Ameli's konnector to match the last website version

---

client/app/views/konnector.coffee

Fix root folder not available

---

client/app/views/konnector.coffee

Fix import button not disabled on click

---

server/konnectors/voyages_sncf.js

Fix crash of SNCF konnector

---

server/konnectors/aprr.js

from issue https://github.com/cozy-labs/konnectors/issues/351

fixing "return" issue on function customSaveDataAndFile aprr

---

server/konnectors/vente_privee.js

from issue https://github.com/cozy-labs/konnectors/issues/351

fixing "return" issue on function customSaveDataAndFile vente privee

---

server/konnectors/sfr_mobile.js

I guess the webpage had an issue, this PR checks the url is incorrect nonetheless to avoid the connector to enter in a loop by being stuck in "importing".

Fix SFR mobile undefined urls (#497)

---

scripts/build.sh

Useful in case of change of name of konnector. #523

Clean server to ensure old konnectors are deleted

---

tests/konnector_structure.coffee
tests/locales.coffee

The failing tests are normal, there is a problem with the virgin mobile konnector. Should be fixed with #520

Add tests over konnector structure. Fixes #437. Fixes #475

---

server/init/konnectors.coffee

Otherwise app will crash on first install

Fix online_net migration

---

client/app/views/styles/_responsive.styl

Fix scroll on mobile

---

README.md
client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/meetup.js
tests/konnector_structure.coffee
tests/lib_konnector_hash.coffee

This PR adds a new konnector which will fetch the Meetup iCal of the user and display it in the Calendar app.
This was mainly made during a Cozy Meetup (how convenient :grinning: !)

Adds a Meetup konnector

---

docs/client-side-architecture.md

This PR introduces a technical doc about a revamp of the client-side application. Its main goal is to get feedback about technical choices, and let contributors make suggestions about our choices and their needs.

Client-side architecture proposal

---

.tx/config
scripts/build.sh

This PR set Transifex to manage locales, targeted on [`MyAccounts.client` resource](https://www.transifex.com/cozy/myaccounts/dashboard/).

Move locales on Transifex

---

.editorconfig
package.json
scripts/build.sh
server/lib/get_template_ext.coffee
server/views/index.pug

This PR add config and upgrade template engine

Upgrade and improve tooling

---

docs/client-side-architecture.md

This is a re-send of #531, because this last one was lost on master branch.I submit this one on `development`, as it concerns the new version of the app.

Re-send #531

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
server/konnectors/birthdays.js

* Fix typos in description and update it according to latest changes.
* Make the `tag` field optional, defaulting to selecting all contacts
when the `tag` field is empty.
Closes #492.

Enhance birthdays konnector

---

package.json

@m4dz the `eslint` package had not been updated for some reason in my last PR. Everything should be in order now, truly sorry about it...

Fix NPM dependencies

---

client/app/routes.js

Fix routing redirection

---

.transifexrc.tpl
.travis.yml
client/app/locales/en.json
client/app/routes.js
client/test/index.js
package.json
server/controllers/index.coffee
server/init/konnectors.coffee
server/konnectors/trainline.js
server/lib/base_konnector.js
server/lib/filter_existing.coffee
tests/konnector_structure.coffee
tests/lib_filter_existing.coffee
tests/lib_link_bank_operation.coffee
tests/lib_save_data_and_file.coffee
tests/locales.coffee
tests/models_bank_operation.coffee
tests/models_file.coffee
tests/patch_commits.coffee
tests/rescuetime.coffee

It's difficult to maintain konnector environment because of tests that are broken; here is the list of broken test to fix:

Fix test broken on travis

---

client/app/views/konnector.coffee
server/controllers/index.coffee
server/models/user.coffee

This PR mask the link to the Files folder from the konnector view, when user hadn't completed the onboarding. This way, the link isn't displayed in the embed view in onboarding, it prevents to navigate to an unavailable app from onboarding step.

Mask link to Files

---

client/app/assets/images/sprites/konnectors-services-sprite.svg
client/app/views/styles/_icons.styl

slug: maif, edf
@jacquarg: Pour les icons de Orange, je te propose s'utiliser la même icone pour tous les services. Nous repasserons dessus une fois la nouvelle version de Mes Comptes sortie.

add maif and edf icons

---

client/app/locales/en.coffee
client/app/locales/fr.coffee
client/app/views/konnector.coffee
package.json
server/controllers/konnectors.coffee
server/konnectors/maif.js

This is the konnector for Maif data. It has been realised by developers from Maif (see https://github.com/cozy-MAIF/konnectors). But we haven't been explicit enough about the procedure of integration of the konnectors and so, to save some time, I am doing this integration for them.
I know there is still work to do on it:
There is also an issue about data model, code could be simplified (request-json ...), or write in a more konnector way. But there is already one app using this data as is (https://github.com/cozy-MAIF/mes-infos-maif), and we are very close a big milestone ; so I propose to work on that later, with Maif and you, simultaneously on their app and the konnector.

Official Maif Konnector (MesInfos)

---

server/konnectors/edf.coffee
server/models/client.coffee
server/models/consumptionstatement.coffee
server/models/contract.coffee
server/models/home.coffee
server/models/paymentterms.coffee
server/models/requests.coffee

Fix an possible future bug on cozydb request missing, by moving models to server/models.
Improve fetch success, adding a retry.

Improve EDF konnector quality

---

client/app/components/DiscoveryList.jsx
client/app/components/UseCasesList.jsx
client/app/index.jsx
client/app/styles/index.styl

Fix use cases image and title translation

---

client/app/components/AccountDialog.jsx
client/app/components/UseCaseDialog.jsx
client/app/styles/index.styl

This PR add a separator to handle the outside click to close a dialog

Handle click outside to close dialogs

---

client/app/components/AccountConnectionForm.jsx
client/app/components/Field.jsx
client/app/lib/accountsHelper.js
client/app/lib/statefulForm.jsx
docs/client-side-connector-configuration.md

Dropdown field type

---

client/app/locales/en.json
client/app/styles/index.styl

Minor Fix to sidebar styles and texts

---

client/app/components/AccountManagement.jsx
client/app/containers/ConnectorManagement.jsx
client/app/locales/en.json
client/app/styles/index.styl

Fixes for the connector configuration

---

.editorconfig
client/app/styles/index.styl

Stick menu's style to the mockups & CSS clean up to stick to the guidelines

CSS clean up & Fix some sidebar styles

---

server/konnectors/soyoustart_eu.coffee

I <3 CozyCloud & thank you for your work :)

Add API account for SoYouStartEU Cozy Konnector

---

server/konnectors/orange_mobile.js
server/konnectors/orange_vod.js
server/models/videostream.coffee

Sorry, the first version of Orange_VOD isn't available yet, but the first API changes are already there.

Update Orange_VOD for API changes

---

server/konnectors/edf.coffee

Fix #670 :
* fix connector stop if no consumption statements available
* fix empty notification even if nothing were added.
* add day to bill file name (ex 2016-12-18-facture_EDF.pdf
* reduce to warning level, log about no edelia data.
Do I miss something ?

Fixes on EDF konnector

---

server/konnectors/freemobile.coffee

Should fix #672. This is not tested (I do not have multiline for Free mobile). So this is a blind fix.

[fix] Fix test if this is a multiline account

---

client/app/components/Field.jsx
client/app/containers/ConnectorManagement.jsx
server/konnectors/edf.coffee

Display the konnector default folder path in the location dropdown field
The 'Open in Files' button opens the selected folder

Fix open in files btn

---

server/konnectors/podcast.js

Fix some crashes

---

client/app/locales/en.json
package.json
server/konnectors/digiposte.js
server/lib/save_data_and_file.coffee
server/models/file.coffee

A new digiposte konnector but this time without build files
Cancel and replaces #724

New digiposte konnector

---

server/models/konnector.coffee
tests/password.coffee

Fix encryption of passwords for konnectors with object format for fields
